# Generated by Django 5.1.11 on 2025-08-15 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_stockquote_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockquote',
            old_name='value',
            new_name='volume',
        ),
    ]
