# Generated by Django 5.1.11 on 2025-08-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_rename_value_stockquote_volume'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockquote',
            unique_together={('company', 'time')},
        ),
    ]
